build: false
environment:
  matrix:
    - TOXENV: check
    - TOXENV: "2.7"
    - TOXENV: "2.7-nocover"
    - TOXENV: "3.4"
    - TOXENV: "3.4-nocover"
init:
  - "ECHO %TOXENV%"
  - ps: "ls C:\\Python*"
install:
  - Reg.exe add "HKCU\Software\Sysinternals\Handle" /v "EulaAccepted" /t REG_DWORD /d "1" /f
  - ps: Invoke-WebRequest "http://live.sysinternals.com/handle.exe" -OutFile "c:\\handle.exe"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - c:\\python34\\python c:\\ez_setup.py
  - c:\\python34\\python c:\\get-pip.py
  - c:\\python34\\Scripts\\pip install virtualenv tox || c:\\handle.exe C:\\Users\\appveyor\\AppData\\Local\\Temp
test_script:
  - "c:\\python34\\Scripts\\tox --version"
  - "c:\\python34\\Scripts\\virtualenv --version"
  - "c:\\python34\\Scripts\\pip --version"
  - "c:\\python34\\Scripts\\tox"
